FIxed import statements
nepalcodes/nepalingo pull request #176
Opened 2024-08-01 08:54 UTC by SansCaar

solves #160

2024-08-02 13:21 UTC, binamkayastha requested changes
Some import statements are still not using relative imports:
 - ChangeLangauges.tsx Menu
 - ActivityCard.tsx Button
 - About.tsx Header
 - Main.ts index 
 
 Please double check that you have all import changed to relative imports

2024-08-04 06:56 UTC, christikaes approved these changes

2024-08-04 07:47 UTC, SansCaar reviewed
The changes are done, I don't know why isn't it letting me merge this

2024-08-04 10:01 UTC, binamkayastha approved these changes
Sorry I thought I approved it already my bad

2024-08-04 10:01 UTC, merged