Adding Tajpuriya data CSV file
nepalcodes/nepalingo pull request #61
Opened 2024-07-05 11:51 UTC by Thepuja

2024-07-05 11:54 UTC, christikaes commented on Tajpuriya grammer - Sheet1.csv
> +English,Tajpuriya/Rajbanshi,English,Tajpuriya/Rajbanshi
Can you please remove the duplicate header - there should only be one for English and one for Tajpuriya

2024-07-05 11:55 UTC, christikaes requested changes

2024-07-05 11:55 UTC, christikaes commented on Tajpuriya grammer - Sheet1.csv
> +English,Tajpuriya/Rajbanshi,English,Tajpuriya/Rajbanshi
When you do this make sure that the extra commas on lines 2-end are removed

2024-07-05 14:20 UTC, christikaes requested changes

2024-07-05 14:20 UTC, christikaes commented on Tajpuriya grammer - Sheet1.csv
> +Go,जा ,
I think there is still an extra space and comma here, it should be: `Go,जा` not `Go,जा ,` the newline is parsed as a new entry so we don't need the comma

2024-07-05 14:20 UTC, christikaes commented on Tajpuriya grammer - Sheet1.csv
Can we also rename this file to `TajpuriyaGrammer.csv`?

2024-07-05 20:25 UTC, christikaes approved these changes

2024-07-05 20:25 UTC, christikaes commented on Tajpuriya grammer - Sheet1.csv
We can do this in a followup PR if you want to merge now

2024-07-06 15:06 UTC, binamkayastha commented
Merging even if the ci/cd is failing, because we know this is safe to merge in (it won't effect the ci/cd)

2024-07-06 15:06 UTC, merged