Hook for using APi for translation
nepalcodes/nepalingo pull request #69
Opened 2024-07-06 14:21 UTC by SansCaar

2024-07-06 15:07 UTC, christikaes commented on nepalingo-web/.env.example
Can you add a small comment explaining what this file will be used for in the future?

2024-07-06 15:16 UTC, christikaes requested changes

2024-07-06 15:16 UTC, christikaes commented on nepalingo-web/src/hooks/useDictionary.tsx
> +]
add in 'maithili'

2024-07-06 15:16 UTC, christikaes commented on nepalingo-web/src/hooks/useDictionary.tsx
> +        meaning: string,
rename to meaningOriginal?

naming convention camelCase
`meaningNP`, `meaningEN`

2024-07-06 15:16 UTC, christikaes commented on nepalingo-web/.env.example
Let's rename this `VITE_BASE_URL` -> `VITE_NEPALBHASA_API_URL` ??

2024-07-06 15:59 UTC, christikaes commented on nepalingo-web/.gitignore
> +.env
let's not gitignore the .env file since I don't want each person to need additional setup steps on their local development machine

2024-07-06 16:00 UTC, christikaes requested changes
Just a small request to not gitignore the .env

2024-07-06 16:21 UTC, christikaes commented on nepalingo-web/src/App.tsx
Did you mean to change this file? I don't thin you need these changes right?

2024-07-06 16:39 UTC, SansCaar commented on nepalingo-web/src/App.tsx
yeah i dont need it so i do i revert it

2024-07-07 03:02 UTC, merged

2024-07-07 18:13 UTC, binamkayastha commented
closed [#42](https://github.com/nepalcodes/nepalingo/issues/42)