added useQuote hook
nepalcodes/nepalingo pull request #88
Opened 2024-07-09 11:18 UTC by NancyAanchal

I tried a bunch of methods but this is the only one that worked. it works but it prints the quote 2 times, I couldn't figure out why.
also moved tajpuriyaquotes.txt to src/quotes/ and renamed it 'tajpuriya.txt' cuz otherwise the path of it from hook would be complex.

2024-07-09 18:04 UTC, christikaes commented on nepalingo-web/src/hooks/useNewari.tsx
> +  let { data, error, isLoading } = useSWR(
looks like your branch might be out of date - can you merge in main into this branch (or rebase) ?

2024-07-09 18:07 UTC, christikaes requested changes
This looks good! I would just recommend a small change to switch to csv format instead of txt

2024-07-09 18:07 UTC, christikaes commented on nepalingo-web/src/quotes/tajpuriya.txt
Can we reformat this into .csv format? I think that will make it easier to edit - eg open in excel etc

2024-07-09 18:15 UTC, NancyAanchal commented on nepalingo-web/src/quotes/tajpuriya.txt
'small' change? well wouldn't it mean reshaping the whole code 😭? I will try to do that tho!

2024-07-10 15:53 UTC, christikaes commented on nepalingo-web/src/hooks/useQuotes.tsx
> +            text: text ? text.trim().replace(/(^"|"$)/g, "") : "",
I don't think you need this anymore right? there are no | separators?

2024-07-10 15:54 UTC, christikaes requested changes
A few small cleanup left

2024-07-10 15:54 UTC, christikaes commented on nepalingo-web/src/quotes/tajpuriya.txt
you did it! it looks good, just looks like you have a little bit of stale logic here

2024-07-11 06:03 UTC, binamkayastha commented on nepalingo-web/src/quotes/tajpuriya.txt
Yeah our bad, we should have made sure it was a CSV beforehand.

2024-07-13 14:55 UTC, christikaes commented
Closing because these changes got merged in the #91 PR

2024-07-13 14:55 UTC, closed without merging