implemented getTajpuriya function
nepalcodes/nepalingo pull request #97
Opened 2024-07-12 15:04 UTC by Thepuja

2024-07-13 06:20 UTC, Thepuja reviewed
fixed the error in line 33 and 26 changed file path

2024-07-13 12:44 UTC, christikaes commented on nepalingo-web/src/hooks/getTajpuriya.tsx
> +  const csvfilepath = fs.readFile('Tajpuriya grammer - Sheet1.csv','utf8');
This is the server side fetching logic that I mentioned in our 1-1 yesterday. Use the `fetch` function instead

2024-07-13 12:46 UTC, christikaes requested changes
This looks pretty close! Nice job. I left a few comments

2024-07-13 12:46 UTC, christikaes commented on nepalingo-web/src/hooks/getTajpuriya.tsx
> +const getTajpuria = (props: Omit<DictionaryProps, 'language'>) => {
Here we shouldn't omit the language - your response has language on like 37 so you don't need this

2024-07-13 12:46 UTC, christikaes commented on nepalingo-web/src/hooks/getTajpuriya.tsx
> +const getTajpuria = (props: Omit<DictionaryProps, 'language'>) => {
This should be renamed to `useTajpuria` since it is a hook (there is a useSWR inside of it)

2024-07-15 10:00 UTC, NancyAanchal commented on nepalingo-web/src/hooks/getTajpuriya.tsx
const sourceFile = "./Tajpuriya grammer - Sheet1.csv";

for this file path to work, u should move ur csv file to the public folder. 
make a 'dictionaries' folder in public and put ur csv file in it. then change the file path to  './dictionaries/Tajpuriya grammer - Sheet1.csv'

2024-07-15 13:05 UTC, christikaes approved these changes
Thanks for fixing these changes!

2024-07-15 13:07 UTC, merged